# -*- coding: utf-8 -*-
"""SIT-TBD CLASSIFIER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vz0w7zeQcznmYRdEyrrrAakq6XMTM18Q
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the dataset
data = pd.read_csv('SIT Thingy - Crop2.csv')  # Replace with your dataset path
print(data)

# Convert categorical variables into numerical using one-hot encoding
data_encoded = pd.get_dummies(data, columns=['season', 'weather', 'soil_type', 'growth_cycle', 'water_requirement', 'nutrient_requirement', 'pests', 'diseases', 'irrigation_type', 'market_demand', 'profitability'])

# # Separate features (X) and labels (y)
# X = data_encoded.drop(['crop_type', 'crop_variety'], axis=1)
X = data_encoded
y = data_encoded['crop_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train,y_train)

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = rf_classifier.predict(X_test)

print(y_pred)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")